server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
      mongodb:
        uri: mongodb://root:123@localhost:27017
        database: xc_cms
rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /